# Dart linter
include: package:lints/recommended.yaml

# Flutter linter
#include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    unused_import: error
    prefer_single_quotes: error
    avoid_print: error
    prefer_const_constructors: error
    prefer_final_locals: error
    unnecessary_null_comparison: error

linter:
  rules:
    - avoid_slow_async_io
    - avoid_type_to_string
    - recursive_getters