// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbpYwsQokg1oYSRMn-TelUAoDmygaWKHU',
    appId: '1:122237698215:web:ef85a3981aa2df70901b82',
    messagingSenderId: '122237698215',
    projectId: 'medex-9ae38',
    authDomain: 'medex-9ae38.firebaseapp.com',
    storageBucket: 'medex-9ae38.appspot.com',
    measurementId: 'G-8WJVZL3716',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3_qEtp1eeUFwyeF-9LPNpXMeG_WEsEP4',
    appId: '1:122237698215:android:2a3fe1c0659789a0901b82',
    messagingSenderId: '122237698215',
    projectId: 'medex-9ae38',
    storageBucket: 'medex-9ae38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxmshwKqPBEooKmSr8AXcDQtBkk22Ugg0',
    appId: '1:122237698215:ios:3c8128d885a230df901b82',
    messagingSenderId: '122237698215',
    projectId: 'medex-9ae38',
    storageBucket: 'medex-9ae38.appspot.com',
    iosClientId: '122237698215-s1dr8rgj6n89jcr2bafeutfq4ddhd204.apps.googleusercontent.com',
    iosBundleId: 'com.example.medex.clinic.medex',
  );
}
